/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CurrentTime: typeof import('./components/CurrentTime.vue')['default']
    LiveTvFooter: typeof import('./components/LiveTvFooter.vue')['default']
    ReplayFooter: typeof import('./components/ReplayFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TvEvent: typeof import('./components/TvEvent.vue')['default']
  }
}
